version: '3'
services:
    postgres:
        image: postgres:alpine
        container_name: postgres_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: nhn
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: todolist
        volumes:
            - ./db-data:/var/lib/postgresql/data